githubRepoOwner: carvierdotdev
githubRepoName: prismic-nextjs
githubHost: github.com
githubRemote: origin
githubBranch: main
requireChecks: false
requireApproval: false
mergeMethod: merge
mergeQueue: false
forceFetchTags: false
showPrTitlesInStack: true
branchPushIndividually: false
